spring.application.name=academy_crm

# Bazaga ulanish
spring.datasource.url=jdbc:postgresql://localhost:5432/academy_crm
spring.datasource.username=javohir
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect